# Generated by Django 4.1.2 on 2022-11-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_neworder_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='mobille_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
