# Generated by Django 4.1.2 on 2022-11-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productbrand_brand_id_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='cat_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
