# Generated by Django 4.1.2 on 2022-11-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productcategory_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_sold',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
