# Generated by Django 4.1.2 on 2022-11-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_last_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_sold',
            field=models.DateField(blank=True, null=True),
        ),
    ]
